name: locationrealtime
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.0.8
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  intl: ^0.18.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  random_avatar: ^0.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true