// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFvpsQIzAvGB6cI1KRpVxdTkdSzhSP6Y',
    appId: '1:859885621505:web:5950a1373fc43eb49e8b00',
    messagingSenderId: '859885621505',
    projectId: 'locationrealtime-30c51',
    authDomain: 'locationrealtime-30c51.firebaseapp.com',
    databaseURL: 'https://locationrealtime-30c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationrealtime-30c51.firebasestorage.app',
    measurementId: 'G-T2XDLRDSEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNAvkGQb9LoO_gvx8JFnPbyVCUuQy4hw',
    appId: '1:859885621505:android:84745678410ce68e9e8b00',
    messagingSenderId: '859885621505',
    projectId: 'locationrealtime-30c51',
    databaseURL: 'https://locationrealtime-30c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationrealtime-30c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3tJXRDwrZOC_Sea574lvI6fbR1zHVQpk',
    appId: '1:859885621505:ios:6289b52ee74805169e8b00',
    messagingSenderId: '859885621505',
    projectId: 'locationrealtime-30c51',
    databaseURL: 'https://locationrealtime-30c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationrealtime-30c51.firebasestorage.app',
    iosBundleId: 'com.example.locationrealtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3tJXRDwrZOC_Sea574lvI6fbR1zHVQpk',
    appId: '1:859885621505:ios:6289b52ee74805169e8b00',
    messagingSenderId: '859885621505',
    projectId: 'locationrealtime-30c51',
    databaseURL: 'https://locationrealtime-30c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationrealtime-30c51.firebasestorage.app',
    iosBundleId: 'com.example.locationrealtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFvpsQIzAvGB6cI1KRpVxdTkdSzhSP6Y',
    appId: '1:859885621505:web:8b7edf3d6525c20a9e8b00',
    messagingSenderId: '859885621505',
    projectId: 'locationrealtime-30c51',
    authDomain: 'locationrealtime-30c51.firebaseapp.com',
    databaseURL: 'https://locationrealtime-30c51-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locationrealtime-30c51.firebasestorage.app',
    measurementId: 'G-KFCE8G7MLW',
  );
}
